// Mocks generated by Mockito 5.2.0 from annotations
// in english_words_trainer/test/features/vocabulary/presentation/bloc/words_list/words_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:english_words_trainer/core/errors/failures.dart' as _i6;
import 'package:english_words_trainer/features/vocabulary/domain/entities/word_entity.dart'
    as _i7;
import 'package:english_words_trainer/features/vocabulary/domain/repositories/vocabulary_repository.dart'
    as _i2;
import 'package:english_words_trainer/features/vocabulary/domain/usecases/add_new_word.dart'
    as _i8;
import 'package:english_words_trainer/features/vocabulary/domain/usecases/get_words_list.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeVocabularyRepository_0 extends _i1.Fake
    implements _i2.VocabularyRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetWordsList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWordsList extends _i1.Mock implements _i4.GetWordsList {
  MockGetWordsList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VocabularyRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeVocabularyRepository_0()) as _i2.VocabularyRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.WordEntity>>> call(
          _i4.GetWordsParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, List<_i7.WordEntity>>>.value(
                      _FakeEither_1<_i6.Failure, List<_i7.WordEntity>>()))
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.WordEntity>>>);
}

/// A class which mocks [AddNewWord].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewWord extends _i1.Mock implements _i8.AddNewWord {
  MockAddNewWord() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VocabularyRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeVocabularyRepository_0()) as _i2.VocabularyRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WordEntity>> call(
          _i8.AddNewWordParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.WordEntity>>.value(
              _FakeEither_1<_i6.Failure, _i7.WordEntity>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.WordEntity>>);
}
