include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    directives_ordering: true
    eol_at_end_of_file: true
