// Mocks generated by Mockito 5.2.0 from annotations
// in english_words_trainer/test/features/vocabulary/data/repositories/word_description_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:english_words_trainer/features/vocabulary/data/datasources/word_api_datasource.dart'
    as _i3;
import 'package:english_words_trainer/features/vocabulary/data/models/word_description_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWordDescriptionModel_0 extends _i1.Fake
    implements _i2.WordDescriptionModel {}

/// A class which mocks [WordApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordApiDataSource extends _i1.Mock implements _i3.WordApiDataSource {
  MockWordApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WordDescriptionModel> getWordDescription(String? word) =>
      (super.noSuchMethod(Invocation.method(#getWordDescription, [word]),
              returnValue: Future<_i2.WordDescriptionModel>.value(
                  _FakeWordDescriptionModel_0()))
          as _i4.Future<_i2.WordDescriptionModel>);
}
