// Mocks generated by Mockito 5.2.0 from annotations
// in english_words_trainer/test/features/vocabulary/domain/usecases/get_word_description_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:english_words_trainer/core/errors/failures.dart' as _i5;
import 'package:english_words_trainer/features/vocabulary/domain/entities/word_api_description_entity.dart'
    as _i6;
import 'package:english_words_trainer/features/vocabulary/domain/repositories/word_description_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [WordDescriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordDescriptionRepository extends _i1.Mock
    implements _i3.WordDescriptionRepository {
  MockWordDescriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WordApiDescriptionEntity>>
      getDescription(String? word) => (super.noSuchMethod(
          Invocation.method(#getDescription, [word]),
          returnValue: Future<
                  _i2.Either<_i5.Failure, _i6.WordApiDescriptionEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.WordApiDescriptionEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.WordApiDescriptionEntity>>);
}
