// Mocks generated by Mockito 5.2.0 from annotations
// in english_words_trainer/test/features/profile/domain/usecases/get_profile_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:english_words_trainer/core/errors/failures.dart' as _i5;
import 'package:english_words_trainer/features/profile/domain/entities/profile_entity.dart'
    as _i6;
import 'package:english_words_trainer/features/profile/domain/repositiroes/profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> createProfile(
          String? userId) =>
      (super.noSuchMethod(Invocation.method(#createProfile, [userId]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.ProfileEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> updateProfile(
          _i6.ProfileEntity? profile) =>
      (super.noSuchMethod(Invocation.method(#updateProfile, [profile]),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
              _FakeEither_0<_i5.Failure, _i6.ProfileEntity>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity?>> getProfileById(
          String? id) =>
      (super.noSuchMethod(Invocation.method(#getProfileById, [id]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.ProfileEntity?>>.value(
                      _FakeEither_0<_i5.Failure, _i6.ProfileEntity?>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity?>>);
}
